### ISSUE TITLE
Configure Okta access via secrets

### ISSUE THREAD

**Issue by fanfoni** [cloudhut/charts#21]
There's any way to use secrets for okta authentication?
I have tried to edit the chart in a fork following the other authentication methods, but maybe I'm not using the right variable names at the deployment template when mounting the secrets.

**Comment by nirsv** [comment]
Hey,
Any update with this?
I am looking for deploying the kowl business solution in my company, but lack of "okta" support is a blocker.
Thanks

**Comment by weeco** [comment]
Hey @nirsv and @fanfoni ,
I committed https://github.com/cloudhut/charts/commit/5364e0f2f038c8d336f659c0262ac7f7f8efe330 . Can you give it a try? I released a new chart version

**Comment by nirsv** [comment]
Thanks @weeco  for the quick reply.
For some reason I get the following error (although I configured it both on secret and values.yaml):
flag provided but not defined: -login.okta.directory.api-token

**Comment by weeco** [comment]
@nirsv Thank you for testing so quickly. I noticed the flag is not named correctly in Kowl Business. It currently expects `-login.okta.api-token` instead of the documented flag `-login.okta.directory.api-token`.

I just released v1.5.1 (`quay.io/cloudhut/kowl-business:v1.5.1`) which correctly parses the flags as documented.

**Comment by nirsv** [comment]
@weeco Thanks. It passed that error but now I get:
container "kowl" in pod "kowl-business-7b957c9856-g48dp" is waiting to start: CreateContainerConfigError

**Comment by weeco** [comment]
@nirsv That's weird because the first issue is emitted from the container (which means it was able to start) and the second one is from Kubernetes indicating that something is wrong with the manifest. Could you describe the pod and provide more information about what is going on?

**Comment by nirsv** [comment]
@weeco so after changing it I got the error: 
Error: couldn't find key login-okta-directory-api-token in Secret kowl/kowl-business


I didn't understand if I should use a secret or values.yaml or both

**Comment by weeco** [comment]
> @weeco so after changing it I got the error: Error: couldn't find key login-okta-directory-api-token in Secret kowl/kowl-business
> 
> I didn't understand if I should use a secret or values.yaml or both

You can use either case. Either you can use an existing secret, but then you are required to provide all the expected secret keys as documented in the values.yaml file. But you can also provide the secrets via the values.yaml file. I would assume you are using the existingSecret option at the moment and it's lacking the expected keys

**Comment by nirsv** [comment]
@weeco When I use only secret (with flag login-okta-directory-api-token or login-okta-api-token) I get the error:
flag provided but not defined: -login.okta.directory.api-token

When I use only on values.yaml and on secret.yaml I get the error:
Error: couldn't find key login-okta-directory-api-token in Secret kowl/kowl-business

Please advise

**Comment by weeco** [comment]
> flag provided but not defined: -login.okta.directory.api-token

That log message comes from the Go process / Kowl Business (unless you are using the wrong docker image?). Please make sure you are running v1.5.1. I thought you said that this version no longer throws that error?

> When I use only on values.yaml and on secret.yaml I get the error:
Error: couldn't find key login-okta-directory-api-token in Secret kowl/kowl-business

That doesn't make sense to me, because you can definetely see it here: https://github.com/cloudhut/charts/blob/8b47f9fe4a3488d33b2e6a4303195a78dc892baf/kowl/templates/secret.yaml#L32 . Anyways this is not necessarily Kowl specific, but rather Kubernetes specific. Could you try to figure out what's the reason for this issue? Make sure you are using the right chart version. If you are stuck you could also come and chat via our discord server (check the Kowl repo for the link). I guess that would be a little bit easier for debugging it then.
